"use client";

import { useState } from "react";
import type { Folder, PostWithClicks } from "@/lib/types";
import { ConfirmModal } from "./ConfirmModal";

export function FoldersClient({ folders, posts }: { folders: Folder[]; posts: PostWithClicks[] }) {
  const [name, setName] = useState("");
  const [editing, setEditing] = useState<Record<string, string>>(Object.fromEntries(folders.map((f) => [f.id, f.name])));
  const [deleteFolder, setDeleteFolder] = useState<Folder | null>(null);
  async function createFolder() { if (!name.trim()) return; await fetch("/api/folders", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name }) }); window.location.reload(); }
  async function renameFolder(id: string) { await fetch(`/api/folders/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: editing[id] }) }); window.location.reload(); }
  async function confirmDelete() { if (!deleteFolder) return; await fetch(`/api/folders/${deleteFolder.id}`, { method: "DELETE" }); window.location.reload(); }
  const stats = (folderId: string) => { const list = posts.filter((p) => p.folder_id === folderId); return { count: list.length, today: list.reduce((s,p)=>s+p.clicks_today,0), week: list.reduce((s,p)=>s+p.clicks_7d,0), month: list.reduce((s,p)=>s+p.clicks_30d,0), all: list.reduce((s,p)=>s+p.clicks_all,0), best: [...list].sort((a,b)=>b.clicks_all-a.clicks_all)[0]?.card_headline || "—" }; };
  return <div className="space-y-8"><div><h1 className="text-4xl font-black">Product Folders</h1><p className="mt-2 text-gray-500">Create, rename, delete, and review folder performance.</p></div><div className="rounded-3xl bg-white p-5 shadow-card"><label className="font-bold">Create folder</label><div className="mt-2 flex flex-col gap-2 sm:flex-row"><input value={name} onChange={(e)=>setName(e.target.value)} className="flex-1 rounded-2xl border px-4 py-3" placeholder="Folder name"/><button onClick={createFolder} className="rounded-full brand-gradient px-6 py-3 font-black text-white">Create folder</button></div></div><div className="grid gap-4">{folders.map((folder)=>{ const s = stats(folder.id); return <article key={folder.id} className="rounded-3xl bg-white p-5 shadow-card"><div className="flex flex-col justify-between gap-3 sm:flex-row"><input value={editing[folder.id] || ""} onChange={(e)=>setEditing((v)=>({...v,[folder.id]:e.target.value}))} className="rounded-2xl border px-4 py-3 text-xl font-black"/><div className="flex gap-2"><button onClick={()=>renameFolder(folder.id)} className="rounded-full bg-orange-50 px-4 py-2 font-bold text-orange-700">Rename</button><button onClick={()=>setDeleteFolder(folder)} className="rounded-full bg-red-50 px-4 py-2 font-bold text-red-700">Delete</button></div></div><div className="mt-4 grid gap-3 sm:grid-cols-6"><span>Cards: <b>{s.count}</b></span><span>Today: <b>{s.today}</b></span><span>7-day: <b>{s.week}</b></span><span>30-day: <b>{s.month}</b></span><span>All-time: <b>{s.all}</b></span><span>Best: <b>{s.best}</b></span></div></article>;})}{folders.length === 0 && <div className="rounded-3xl bg-white p-8 text-center shadow-card">No folders yet.</div>}</div><ConfirmModal open={Boolean(deleteFolder)} title="Delete this folder?" onCancel={()=>setDeleteFolder(null)} onConfirm={confirmDelete} confirmLabel="Delete folder"><p>Cards inside this folder will not be deleted. They will be moved to Unfoldered.</p></ConfirmModal></div>;
}
